global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'crowdsec'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['crowdsec-security:6060']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
